### PR TITLE
Implement GitHub Action for building and testing with Bazel.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by SanjayVas** [comment]
This is for world-federation-of-advertisers/experimental#31.

**Review by fashing — APPROVED** [review]

**Comment by oliver-amzn** [comment]
Is it common to check in the whole node_modules directory? (instead of downloading it all add runtime)

**Comment by SanjayVas** [comment]
> Is it common to check in the whole node_modules directory? (instead of downloading it all at runtime)

This looked odd to me too and I had the same thought, but it is indeed the recommended practice for GitHub Actions. See the section in the GitHub Docs for [Creating a JavaScript Action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github).

The mentioned alternative in the GitHub docs is to use `ncc` to "compile" your Node.js package into a single distribution file, but 1. That introduces another manual step and involves checking-in compiled code. 2. Duplicates dependency code between Actions (this uses npm workspaces to share node_modules between Actions). There are some articles<sup>1</sup> I found that discussed running `npm install` in your workflow, but even those suggested that you should only do so for development and should use one of the options mentioned in the GitHub docs for deploying Actions that will be used in multiple repos.

<sup>1</sup> https://jeffrafter.com/releasing-github-actions/

**Comment by oliver-amzn** [comment]
Interesting. Thanks for explaining!

**Pull request merged**
