### PR TITLE
Update Node.js runner and actions dependencies to latest available.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/25)

### CODE REVIEW

**Comment by SanjayVas** [comment]
The node12 runner is deprecated.

**Review by SanjayVas — COMMENTED** [review]
You should be able to ignore everything inside of the `node_modules` folders as those are generated by running `npm install`. (Normally we wouldn't check in generated things like that and instead rely on the build system to do it, but this repo is consumed directly by GitHub Actions so we have no hooks for that.)

Reviewable helpfully groups these under "Vendored" in the file matrix.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/25#-:-NFQNOnE4giYmu9XqzPb:bi3hvq1)* status: 0 of 1874 files reviewed, all discussions resolved

**Review by stevenwarejones — COMMENTED** [review]
Are we able to use something like this? https://github.com/actions/setup-node

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/25#-:-NFToS_T8Sle0__KHq-V:b-h93em3)* status: 0 of 1874 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
I don't think that applies to a custom JS action. We're following the guide here, which says to just check in node_modules or else use something more complicated to "compile" them into a single file (which doesn't help that much in our case): https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/25#-:-NFUYjLz1WiDJq1JdD9L:bg0nizc)* status: 0 of 1874 files reviewed, all discussions resolved

**Review by stevenwarejones — COMMENTED** [review]
Wdyt about using vercel to just check in a single node_modules file: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/25#-:-NFiLFak2wZhnQvFt0zt:b-5pi956)* status: 0 of 1874 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
This PR is focused on just keeping our actions working in the fact of the node12 runner deprecation without changing the implementation. We can discuss options for improving this in the future separately.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/25#-:-NFia23z6H0xC4An6L7Z:b-o9bhu4)* status: 0 of 1874 files reviewed, all discussions resolved

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 1874 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/25)* status: 8 of 1874 files reviewed, all discussions resolved

**Pull request merged**
