### PR TITLE
Decompose bazel-build-test action into multiple actions.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/34)

**Comment by SanjayVas** [comment]
Note that this is a breaking change and warrants a major version bump.

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 34 of 2412 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/34)* status: 34 of 2412 files reviewed, all discussions resolved

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 2378 of 2412 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/actions/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
